import random
import itertools

print("# Automatically generated by atomic_test_gen.py")
print("# Manually edit at your own risk.")

atomics = ["amoadd.w", "amoand.w", "amoor.w", "amoxor.w", "amoswap.w"]
combs = list(itertools.product([2, 3], repeat=2))

n = 0
for atomic in atomics:
    for comb in combs:
        print(f'''
la x1, loc{n}
addi x2, x2, {random.randint(0, 2**11)}
{atomic} x{comb[0]}, x{comb[1]}, (x1)
lw x4, 0(x1)
add x3, x3, x0
add x2, x2, x0
add x1, x1, x0
''')
        n += 1

print('''
halt:
     j halt
''')


for i in range(n):
    print(f"loc{i}: .word {hex(random.randint(0, 2**32))}")

print("# End autogenerate")
