#!/usr/bin/env python3

import sys


if len(sys.argv) != 3:
    print(
        "This program generates a readmemh-compatible memory given a Linux image and a device tree block."
    )
    print(
        "Wrong number of arguments. Usage:\n./fltbin2mem.py path/to/image path/to/dtb"
    )
print(f"// Autogenerated by fltbin2mem.py with arguments {sys.argv[1]}, {sys.argv[2]}")
print("// Start of DTB.")
print("@83fff940")  # Assume DTB is < 5KB
with open(sys.argv[2], "rb") as f:
    while True:
        t = f.read(1)
        if not t:
            break
        print(t.hex())

print("// DTB ends.")
print("// Start of kernel image.")
print("@80000000")
with open(sys.argv[1], "rb") as f:
    while True:
        t = f.read(1)
        if not t:
            break
        print(t.hex())
